export const AUDIT_ACTIONS = [
  'USER_LOGIN',
  'USER_LOGIN_FAILED',
  'USER_LOGOUT',
  'SESSION_ORGANIZATION_SWITCHED',
  'CUSTOMER_CREATED',
  'BRAND_CREATED',
  'TEMPLATE_CREATED',
  'TEMPLATE_UPDATED',
  'TEMPLATE_VERSION_CREATED',
  'TEMPLATE_VERSION_UPDATED',
  'TEMPLATE_STATUS_CHANGED',
  'TEMPLATE_VERSION_STATUS_CHANGED',
  'ASSET_CREATED',
] as const;
export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_RESOURCE_TYPES = [
  'USER',
  'SESSION',
  'CUSTOMER',
  'BRAND',
  'TEMPLATE',
  'TEMPLATE_VERSION',
  'ASSET',
] as const;
export type AuditResourceType = (typeof AUDIT_RESOURCE_TYPES)[number];
