import type { Readable } from 'node:stream';

/**
 * Vendor-neutral object storage contract. Database records store only the opaque `key`;
 * bucket names, endpoints and URLs are configuration, so providers can be swapped
 * (local disk ↔ MinIO ↔ AWS S3 ↔ Cloudflare R2) without data migration of records.
 */
export interface ObjectStorage {
  readonly driver: string;
  putObject(key: string, body: Buffer, options: PutObjectOptions): Promise<void>;
  getObject(key: string): Promise<StoredObject>;
  objectExists(key: string): Promise<boolean>;
  deleteObject(key: string): Promise<void>;
}

export interface PutObjectOptions {
  readonly contentType: string;
  /** Lower-case hex SHA-256 of `body`; providers that support it verify integrity on upload. */
  readonly checksumSha256: string;
}

export interface StoredObject {
  readonly body: Readable;
  readonly contentLength: number | null;
}

export const OBJECT_STORAGE = Symbol('OBJECT_STORAGE');

export class ObjectNotFoundError extends Error {
  constructor(readonly key: string) {
    super(`Object not found: ${key}`);
    this.name = 'ObjectNotFoundError';
  }
}

const KEY_PATTERN = /^[a-z0-9][a-z0-9/_.-]{0,511}$/i;

/** Keys are generated by the platform; this guards against traversal and odd characters anyway. */
export function assertValidObjectKey(key: string): void {
  if (!KEY_PATTERN.test(key) || key.includes('..') || key.includes('//') || key.endsWith('/')) {
    throw new Error(`Invalid object storage key: ${JSON.stringify(key)}`);
  }
}

/** Content-addressed key: identical bytes within an organization share one stored object. */
export function assetStorageKey(organizationId: string, checksumSha256: string): string {
  return `organizations/${organizationId}/assets/sha256/${checksumSha256.slice(0, 2)}/${checksumSha256}`;
}
