import type { SourceCell } from '@smarttag/import-core';
import { describe, expect, it } from 'vitest';
import { isDateFormatCode, parserFor, sourceFromBuffer } from '../src';
import { buildXlsxWorkbook } from '../src/testing';
import { limits, readAllRows, texts, xlsxSettings } from './helpers';

const xlsx = parserFor('XLSX');

const workbook = buildXlsxWorkbook({
  sheets: [
    { name: 'Summary', rows: [['Customer ABC — FW26 order'], ['Generated by ERP']] },
    {
      name: 'Tags',
      rows: [
        ['STYLE', 'PRICE', 'SHIP DATE', 'SUSTAINABLE', 'GTIN', 'TOTAL', 'LABEL', 'PRICE'],
        [
          'YT2045',
          39.95,
          { date: 46280 },
          true,
          { zeroPadded: 12345 },
          { formula: 'B2*2', cached: 79.9 },
          { inline: 'Inline text' },
          42,
        ],
        {
          rowNumber: 4,
          cells: [
            'YT2046',
            '19,99',
            '15/09/2026',
            false,
            { error: '#N/A' },
            { formula: 'B4*2' },
            null,
            21,
          ],
        },
      ],
    },
    { name: 'Hidden', hidden: true, rows: [['secret']] },
  ],
});

describe('XLSX inspection', () => {
  it('lists every worksheet with visibility, counts and a preview', async () => {
    const inspection = await xlsx.inspect(sourceFromBuffer(workbook), xlsxSettings(), limits());
    expect(inspection.format).toBe('XLSX');
    expect(inspection.workbook).toEqual({ date1904: false, externalLinks: false });
    expect(
      inspection.sheets.map((sheet) => [
        sheet.name,
        sheet.visible,
        sheet.nonBlankRows,
        sheet.columnCount,
      ]),
    ).toEqual([
      ['Summary', true, 2, 1],
      ['Tags', true, 3, 8],
      ['Hidden', false, 1, 1],
    ]);
    const tags = inspection.sheets[1]!;
    expect(tags.previewRows.map((row) => row.rowNumber)).toEqual([1, 2, 3, 4]);
    expect(tags.previewRows[2]!.cells).toEqual([]);
    expect(tags.previewRows[1]!.cells.map((cell) => cell.text)).toEqual([
      'YT2045',
      '39.95',
      '2026-09-15',
      'TRUE',
      '0000000012345',
      '79.9',
      'Inline text',
      '42',
    ]);
    expect(tags).toMatchObject({ formulaCells: 2, formulaCellsWithoutValue: 1 });
    expect(tags.issues).toMatchObject([{ code: 'FORMULAS_PRESENT', severity: 'WARNING' }]);
  });
});

describe('XLSX rows keep their stored types', () => {
  it('reads the selected second sheet, never the first by assumption', async () => {
    const rows = await readAllRows(workbook, xlsxSettings('Tags'));
    expect(rows.map((row) => row.rowNumber)).toEqual([1, 2, 4]);
    expect(texts(rows[0])).toEqual([
      'STYLE',
      'PRICE',
      'SHIP DATE',
      'SUSTAINABLE',
      'GTIN',
      'TOTAL',
      'LABEL',
      'PRICE',
    ]);
    const typed: readonly SourceCell[] = rows[1]!.cells;
    expect(typed).toEqual([
      { kind: 'TEXT', text: 'YT2045' },
      { kind: 'NUMBER', value: 39.95 },
      { kind: 'DATE', date: '2026-09-15', time: null },
      { kind: 'BOOLEAN', value: true },
      { kind: 'NUMBER', value: 12345, zeroPad: 13 },
      { kind: 'NUMBER', value: 79.9, formula: true },
      { kind: 'TEXT', text: 'Inline text' },
      { kind: 'NUMBER', value: 42 },
    ]);
  });

  it('text dates stay text, blank cells are empty, formulas without a cached result are empty formulas', async () => {
    const rows = await readAllRows(workbook, xlsxSettings('Tags'));
    expect(rows[2]!.cells).toEqual([
      { kind: 'TEXT', text: 'YT2046' },
      { kind: 'TEXT', text: '19,99' },
      { kind: 'TEXT', text: '15/09/2026' },
      { kind: 'BOOLEAN', value: false },
      { kind: 'ERROR', code: '#N/A' },
      { kind: 'EMPTY', formula: true },
      { kind: 'EMPTY' },
      { kind: 'NUMBER', value: 21 },
    ]);
  });

  it('converts typed dates in the 1904 date system and keeps times of day', async () => {
    const mac = buildXlsxWorkbook({
      date1904: true,
      sheets: [
        { name: 'Dates', rows: [['D'], [{ date: 44818 }], [{ date: 44818.75, withTime: true }]] },
      ],
    });
    const inspection = await xlsx.inspect(sourceFromBuffer(mac), xlsxSettings(), limits());
    expect(inspection.workbook?.date1904).toBe(true);
    const rows = await readAllRows(mac, xlsxSettings('Dates'));
    expect(rows[1]!.cells).toEqual([{ kind: 'DATE', date: '2026-09-15', time: null }]);
    expect(rows[2]!.cells).toEqual([{ kind: 'DATE', date: '2026-09-15', time: '18:00:00' }]);
  });

  it('decodes XML escapes, _xHHHH_ escapes and non-Latin text', async () => {
    const book = buildXlsxWorkbook({
      sheets: [
        {
          name: 'Text',
          rows: [['A & B <c> "d"', 'line_x000D__x000A_break', 'বাংলা', { inline: '  padded  ' }]],
        },
      ],
    });
    const rows = await readAllRows(book, xlsxSettings('Text'));
    expect(texts(rows[0])).toEqual(['A & B <c> "d"', 'line\r\nbreak', 'বাংলা', '  padded  ']);
  });

  it('notes merged cells', async () => {
    const merged = buildXlsxWorkbook({
      sheets: [
        {
          name: 'M',
          rows: [
            ['A', 'B'],
            ['1', '2'],
          ],
          mergedCells: ['A1:B1'],
        },
      ],
    });
    const inspection = await xlsx.inspect(sourceFromBuffer(merged), xlsxSettings(), limits());
    expect(inspection.sheets[0]!.issues).toMatchObject([{ code: 'MERGED_CELLS_PRESENT' }]);
  });
});

describe('date format codes', () => {
  it.each([
    ['dd/mm/yyyy', true],
    ['yyyy\\-mm\\-dd', true],
    ['[$-409]mmmm d, yyyy;@', true],
    ['h:mm AM/PM', true],
    ['[h]:mm:ss', true],
    ['General', false],
    ['0.00', false],
    ['#,##0.00 "days"', false],
    ['"Month" 0', false],
    ['[Red]0.00', false],
    ['0000000000000', false],
    ['@', false],
  ])('%s → %s', (code, date) => {
    expect(isDateFormatCode(code)).toBe(date);
  });
});
