'use client';
import { ROLES, ROLE_LABELS, type AuditEventDto, type MemberAdminDto, type OrganizationAdminDto, type Role, type RoleDefinitionDto } from '@smarttag/shared-types';
import { Alert, Button } from '@smarttag/ui';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { useState, type FormEvent } from 'react';
import { apiRequest, describeError } from '@/lib/api-client';

const input='h-9 rounded-md border border-slate-300 bg-white px-3 text-sm';
export function CompanyAdminView(){
 const qc=useQueryClient(); const q=useQuery({queryKey:['admin','organization'],queryFn:()=>apiRequest<OrganizationAdminDto>('/administration/organization')});
 const [error,setError]=useState(''); const m=useMutation({mutationFn:(x:{name:string;slug:string})=>apiRequest<OrganizationAdminDto>('/administration/organization',{method:'PATCH',json:x}),onSuccess:d=>{qc.setQueryData(['admin','organization'],d);setError('')},onError:e=>setError(describeError(e))});
 if(!q.data)return <Page title="Company">{q.error?<Alert tone="danger">{describeError(q.error)}</Alert>:<p>Loading…</p>}</Page>;
 return <Page title="Company" subtitle="Organization identity used throughout SmartTag."><form className="max-w-xl space-y-4" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);m.mutate({name:String(f.get('name')),slug:String(f.get('slug'))})}}><Field label="Company name"><input className={input+' w-full'} name="name" defaultValue={q.data.name}/></Field><Field label="Slug"><input className={input+' w-full'} name="slug" defaultValue={q.data.slug}/></Field>{error&&<Alert tone="danger">{error}</Alert>}<Button type="submit" loading={m.isPending}>Save company</Button></form></Page>
}
export function UsersAdminView(){
 const qc=useQueryClient(); const q=useQuery({queryKey:['admin','members'],queryFn:()=>apiRequest<MemberAdminDto[]>('/administration/members')}); const [msg,setMsg]=useState('');
 const create=useMutation({mutationFn:(x:unknown)=>apiRequest<MemberAdminDto>('/administration/members',{json:x}),onSuccess:()=>{void qc.invalidateQueries({queryKey:['admin','members']});setMsg('User created.')},onError:e=>setMsg(describeError(e))});
 const patch=useMutation({mutationFn:({id,json}:{id:string;json:unknown})=>apiRequest('/administration/members/'+id,{method:'PATCH',json}),onSuccess:()=>void qc.invalidateQueries({queryKey:['admin','members']}),onError:e=>setMsg(describeError(e))});
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);create.mutate({displayName:f.get('displayName'),email:f.get('email'),password:f.get('password'),role:f.get('role')});}
 return <Page title="Users" subtitle="Create users, assign one primary role, and disable access without deleting history."><form onSubmit={submit} className="mb-6 grid gap-3 rounded-lg border bg-white p-4 md:grid-cols-5"><input required name="displayName" placeholder="Display name" className={input}/><input required type="email" name="email" placeholder="Email" className={input}/><input required minLength={12} type="password" name="password" placeholder="Initial password (12+)" className={input}/><select name="role" className={input}>{ROLES.map(r=><option key={r} value={r}>{ROLE_LABELS[r]}</option>)}</select><Button type="submit" loading={create.isPending}>Create user</Button></form>{msg&&<p className="mb-3 text-sm text-slate-600">{msg}</p>}{q.data?<div className="overflow-x-auto rounded-lg border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><Th>User</Th><Th>Role</Th><Th>Status</Th><Th>Last login</Th></tr></thead><tbody>{q.data.map(u=><tr key={u.membershipId} className="border-t"><td className="p-3"><b>{u.displayName}</b><div className="text-xs text-slate-500">{u.email}</div></td><td className="p-3"><select className={input} value={u.role??''} onChange={e=>patch.mutate({id:u.membershipId,json:{role:e.target.value as Role}})}>{ROLES.map(r=><option key={r} value={r}>{ROLE_LABELS[r]}</option>)}</select></td><td className="p-3"><select className={input} value={u.userStatus} onChange={e=>patch.mutate({id:u.membershipId,json:{status:e.target.value}})}><option>ACTIVE</option><option>DISABLED</option></select></td><td className="p-3 text-slate-500">{u.lastLoginAt?new Date(u.lastLoginAt).toLocaleString():'Never'}</td></tr>)}</tbody></table></div>:<p>Loading…</p>}</Page>
}
export function RolesAdminView(){const q=useQuery({queryKey:['admin','roles'],queryFn:()=>apiRequest<RoleDefinitionDto[]>('/administration/roles')});return <Page title="Roles & permissions" subtitle="System roles are protected; permissions are enforced by the API.">{q.data?<div className="grid gap-4 lg:grid-cols-2">{q.data.map(r=><section key={r.role} className="rounded-lg border bg-white p-4"><h2 className="font-semibold">{r.label}</h2><p className="mb-3 text-xs text-slate-500">System role · {r.permissions.length} permissions</p><div className="flex flex-wrap gap-1">{r.permissions.map(p=><span key={p} className="rounded bg-slate-100 px-2 py-1 text-xs">{p}</span>)}</div></section>)}</div>:<p>Loading…</p>}</Page>}
export function AuditAdminView(){const q=useQuery({queryKey:['admin','audit'],queryFn:()=>apiRequest<AuditEventDto[]>('/administration/audit',{query:{limit:100}})});return <Page title="Audit log" subtitle="Recent organization security and business events.">{q.data?<div className="overflow-x-auto rounded-lg border bg-white"><table className="w-full text-sm"><thead className="bg-slate-50 text-left"><tr><Th>Time</Th><Th>Action</Th><Th>Resource</Th><Th>Actor</Th></tr></thead><tbody>{q.data.map(e=><tr key={e.id} className="border-t"><td className="p-3 whitespace-nowrap">{new Date(e.createdAt).toLocaleString()}</td><td className="p-3 font-medium">{e.action}</td><td className="p-3">{e.resourceType}</td><td className="p-3">{e.actor?.displayName??'System'}</td></tr>)}</tbody></table></div>:<p>Loading…</p>}</Page>}
function Page({title,subtitle,children}:{title:string;subtitle?:string;children:React.ReactNode}){return <div className="mx-auto max-w-6xl space-y-5"><div><h1 className="text-2xl font-semibold">{title}</h1>{subtitle&&<p className="mt-1 text-sm text-slate-600">{subtitle}</p>}</div>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-sm font-medium">{label}</span>{children}</label>}
function Th({children}:{children:React.ReactNode}){return <th className="p-3 font-medium">{children}</th>}
